// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Common.proto

package com.hoolai.ccgames.bi.protocol;

public final class Common {
  private Common() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MessageLoginOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Common.MessageLogin)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string platform = 1;</code>
     */
    boolean hasPlatform();
    /**
     * <code>optional string platform = 1;</code>
     */
    java.lang.String getPlatform();
    /**
     * <code>optional string platform = 1;</code>
     */
    com.google.protobuf.ByteString
        getPlatformBytes();

    /**
     * <code>optional string app_id = 2;</code>
     */
    boolean hasAppId();
    /**
     * <code>optional string app_id = 2;</code>
     */
    java.lang.String getAppId();
    /**
     * <code>optional string app_id = 2;</code>
     */
    com.google.protobuf.ByteString
        getAppIdBytes();

    /**
     * <code>optional string login_name = 3;</code>
     */
    boolean hasLoginName();
    /**
     * <code>optional string login_name = 3;</code>
     */
    java.lang.String getLoginName();
    /**
     * <code>optional string login_name = 3;</code>
     */
    com.google.protobuf.ByteString
        getLoginNameBytes();

    /**
     * <code>optional string login_pass = 4;</code>
     */
    boolean hasLoginPass();
    /**
     * <code>optional string login_pass = 4;</code>
     */
    java.lang.String getLoginPass();
    /**
     * <code>optional string login_pass = 4;</code>
     */
    com.google.protobuf.ByteString
        getLoginPassBytes();

    /**
     * <code>optional int32 msg_ver = 5;</code>
     */
    boolean hasMsgVer();
    /**
     * <code>optional int32 msg_ver = 5;</code>
     */
    int getMsgVer();
  }
  /**
   * Protobuf type {@code Common.MessageLogin}
   */
  public static final class MessageLogin extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Common.MessageLogin)
      MessageLoginOrBuilder {
    // Use MessageLogin.newBuilder() to construct.
    private MessageLogin(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MessageLogin(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MessageLogin defaultInstance;
    public static MessageLogin getDefaultInstance() {
      return defaultInstance;
    }

    public MessageLogin getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MessageLogin(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              platform_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              appId_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              loginName_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              loginPass_ = bs;
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              msgVer_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hoolai.ccgames.bi.protocol.Common.internal_static_Common_MessageLogin_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hoolai.ccgames.bi.protocol.Common.internal_static_Common_MessageLogin_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hoolai.ccgames.bi.protocol.Common.MessageLogin.class, com.hoolai.ccgames.bi.protocol.Common.MessageLogin.Builder.class);
    }

    public static com.google.protobuf.Parser<MessageLogin> PARSER =
        new com.google.protobuf.AbstractParser<MessageLogin>() {
      public MessageLogin parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MessageLogin(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MessageLogin> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int PLATFORM_FIELD_NUMBER = 1;
    private java.lang.Object platform_;
    /**
     * <code>optional string platform = 1;</code>
     */
    public boolean hasPlatform() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string platform = 1;</code>
     */
    public java.lang.String getPlatform() {
      java.lang.Object ref = platform_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          platform_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string platform = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPlatformBytes() {
      java.lang.Object ref = platform_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        platform_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int APP_ID_FIELD_NUMBER = 2;
    private java.lang.Object appId_;
    /**
     * <code>optional string app_id = 2;</code>
     */
    public boolean hasAppId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string app_id = 2;</code>
     */
    public java.lang.String getAppId() {
      java.lang.Object ref = appId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          appId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string app_id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAppIdBytes() {
      java.lang.Object ref = appId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOGIN_NAME_FIELD_NUMBER = 3;
    private java.lang.Object loginName_;
    /**
     * <code>optional string login_name = 3;</code>
     */
    public boolean hasLoginName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string login_name = 3;</code>
     */
    public java.lang.String getLoginName() {
      java.lang.Object ref = loginName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          loginName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string login_name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getLoginNameBytes() {
      java.lang.Object ref = loginName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        loginName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOGIN_PASS_FIELD_NUMBER = 4;
    private java.lang.Object loginPass_;
    /**
     * <code>optional string login_pass = 4;</code>
     */
    public boolean hasLoginPass() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string login_pass = 4;</code>
     */
    public java.lang.String getLoginPass() {
      java.lang.Object ref = loginPass_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          loginPass_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string login_pass = 4;</code>
     */
    public com.google.protobuf.ByteString
        getLoginPassBytes() {
      java.lang.Object ref = loginPass_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        loginPass_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSG_VER_FIELD_NUMBER = 5;
    private int msgVer_;
    /**
     * <code>optional int32 msg_ver = 5;</code>
     */
    public boolean hasMsgVer() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 msg_ver = 5;</code>
     */
    public int getMsgVer() {
      return msgVer_;
    }

    private void initFields() {
      platform_ = "";
      appId_ = "";
      loginName_ = "";
      loginPass_ = "";
      msgVer_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getPlatformBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getAppIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getLoginNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getLoginPassBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, msgVer_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getPlatformBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getAppIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getLoginNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getLoginPassBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, msgVer_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.hoolai.ccgames.bi.protocol.Common.MessageLogin parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hoolai.ccgames.bi.protocol.Common.MessageLogin parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hoolai.ccgames.bi.protocol.Common.MessageLogin parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hoolai.ccgames.bi.protocol.Common.MessageLogin parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hoolai.ccgames.bi.protocol.Common.MessageLogin parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hoolai.ccgames.bi.protocol.Common.MessageLogin parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.hoolai.ccgames.bi.protocol.Common.MessageLogin parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.hoolai.ccgames.bi.protocol.Common.MessageLogin parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.hoolai.ccgames.bi.protocol.Common.MessageLogin parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hoolai.ccgames.bi.protocol.Common.MessageLogin parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hoolai.ccgames.bi.protocol.Common.MessageLogin prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Common.MessageLogin}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Common.MessageLogin)
        com.hoolai.ccgames.bi.protocol.Common.MessageLoginOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hoolai.ccgames.bi.protocol.Common.internal_static_Common_MessageLogin_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hoolai.ccgames.bi.protocol.Common.internal_static_Common_MessageLogin_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hoolai.ccgames.bi.protocol.Common.MessageLogin.class, com.hoolai.ccgames.bi.protocol.Common.MessageLogin.Builder.class);
      }

      // Construct using com.hoolai.ccgames.bi.protocol.Common.MessageLogin.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        platform_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        appId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        loginName_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        loginPass_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        msgVer_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hoolai.ccgames.bi.protocol.Common.internal_static_Common_MessageLogin_descriptor;
      }

      public com.hoolai.ccgames.bi.protocol.Common.MessageLogin getDefaultInstanceForType() {
        return com.hoolai.ccgames.bi.protocol.Common.MessageLogin.getDefaultInstance();
      }

      public com.hoolai.ccgames.bi.protocol.Common.MessageLogin build() {
        com.hoolai.ccgames.bi.protocol.Common.MessageLogin result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hoolai.ccgames.bi.protocol.Common.MessageLogin buildPartial() {
        com.hoolai.ccgames.bi.protocol.Common.MessageLogin result = new com.hoolai.ccgames.bi.protocol.Common.MessageLogin(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.platform_ = platform_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.appId_ = appId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.loginName_ = loginName_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.loginPass_ = loginPass_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.msgVer_ = msgVer_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hoolai.ccgames.bi.protocol.Common.MessageLogin) {
          return mergeFrom((com.hoolai.ccgames.bi.protocol.Common.MessageLogin)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hoolai.ccgames.bi.protocol.Common.MessageLogin other) {
        if (other == com.hoolai.ccgames.bi.protocol.Common.MessageLogin.getDefaultInstance()) return this;
        if (other.hasPlatform()) {
          bitField0_ |= 0x00000001;
          platform_ = other.platform_;
          onChanged();
        }
        if (other.hasAppId()) {
          bitField0_ |= 0x00000002;
          appId_ = other.appId_;
          onChanged();
        }
        if (other.hasLoginName()) {
          bitField0_ |= 0x00000004;
          loginName_ = other.loginName_;
          onChanged();
        }
        if (other.hasLoginPass()) {
          bitField0_ |= 0x00000008;
          loginPass_ = other.loginPass_;
          onChanged();
        }
        if (other.hasMsgVer()) {
          setMsgVer(other.getMsgVer());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hoolai.ccgames.bi.protocol.Common.MessageLogin parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hoolai.ccgames.bi.protocol.Common.MessageLogin) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object platform_ = "";
      /**
       * <code>optional string platform = 1;</code>
       */
      public boolean hasPlatform() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string platform = 1;</code>
       */
      public java.lang.String getPlatform() {
        java.lang.Object ref = platform_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            platform_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string platform = 1;</code>
       */
      public com.google.protobuf.ByteString
          getPlatformBytes() {
        java.lang.Object ref = platform_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          platform_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string platform = 1;</code>
       */
      public Builder setPlatform(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        platform_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string platform = 1;</code>
       */
      public Builder clearPlatform() {
        bitField0_ = (bitField0_ & ~0x00000001);
        platform_ = getDefaultInstance().getPlatform();
        onChanged();
        return this;
      }
      /**
       * <code>optional string platform = 1;</code>
       */
      public Builder setPlatformBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        platform_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object appId_ = "";
      /**
       * <code>optional string app_id = 2;</code>
       */
      public boolean hasAppId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string app_id = 2;</code>
       */
      public java.lang.String getAppId() {
        java.lang.Object ref = appId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            appId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string app_id = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAppIdBytes() {
        java.lang.Object ref = appId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          appId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string app_id = 2;</code>
       */
      public Builder setAppId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        appId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string app_id = 2;</code>
       */
      public Builder clearAppId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        appId_ = getDefaultInstance().getAppId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string app_id = 2;</code>
       */
      public Builder setAppIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        appId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object loginName_ = "";
      /**
       * <code>optional string login_name = 3;</code>
       */
      public boolean hasLoginName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string login_name = 3;</code>
       */
      public java.lang.String getLoginName() {
        java.lang.Object ref = loginName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            loginName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string login_name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getLoginNameBytes() {
        java.lang.Object ref = loginName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          loginName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string login_name = 3;</code>
       */
      public Builder setLoginName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        loginName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string login_name = 3;</code>
       */
      public Builder clearLoginName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        loginName_ = getDefaultInstance().getLoginName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string login_name = 3;</code>
       */
      public Builder setLoginNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        loginName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object loginPass_ = "";
      /**
       * <code>optional string login_pass = 4;</code>
       */
      public boolean hasLoginPass() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string login_pass = 4;</code>
       */
      public java.lang.String getLoginPass() {
        java.lang.Object ref = loginPass_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            loginPass_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string login_pass = 4;</code>
       */
      public com.google.protobuf.ByteString
          getLoginPassBytes() {
        java.lang.Object ref = loginPass_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          loginPass_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string login_pass = 4;</code>
       */
      public Builder setLoginPass(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        loginPass_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string login_pass = 4;</code>
       */
      public Builder clearLoginPass() {
        bitField0_ = (bitField0_ & ~0x00000008);
        loginPass_ = getDefaultInstance().getLoginPass();
        onChanged();
        return this;
      }
      /**
       * <code>optional string login_pass = 4;</code>
       */
      public Builder setLoginPassBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        loginPass_ = value;
        onChanged();
        return this;
      }

      private int msgVer_ ;
      /**
       * <code>optional int32 msg_ver = 5;</code>
       */
      public boolean hasMsgVer() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 msg_ver = 5;</code>
       */
      public int getMsgVer() {
        return msgVer_;
      }
      /**
       * <code>optional int32 msg_ver = 5;</code>
       */
      public Builder setMsgVer(int value) {
        bitField0_ |= 0x00000010;
        msgVer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 msg_ver = 5;</code>
       */
      public Builder clearMsgVer() {
        bitField0_ = (bitField0_ & ~0x00000010);
        msgVer_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Common.MessageLogin)
    }

    static {
      defaultInstance = new MessageLogin(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Common.MessageLogin)
  }

  public interface MessageStatusOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Common.MessageStatus)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 status = 1;</code>
     */
    boolean hasStatus();
    /**
     * <code>optional int32 status = 1;</code>
     */
    int getStatus();

    /**
     * <code>optional string description = 2;</code>
     */
    boolean hasDescription();
    /**
     * <code>optional string description = 2;</code>
     */
    java.lang.String getDescription();
    /**
     * <code>optional string description = 2;</code>
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();
  }
  /**
   * Protobuf type {@code Common.MessageStatus}
   */
  public static final class MessageStatus extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Common.MessageStatus)
      MessageStatusOrBuilder {
    // Use MessageStatus.newBuilder() to construct.
    private MessageStatus(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MessageStatus(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MessageStatus defaultInstance;
    public static MessageStatus getDefaultInstance() {
      return defaultInstance;
    }

    public MessageStatus getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MessageStatus(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              status_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              description_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hoolai.ccgames.bi.protocol.Common.internal_static_Common_MessageStatus_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hoolai.ccgames.bi.protocol.Common.internal_static_Common_MessageStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hoolai.ccgames.bi.protocol.Common.MessageStatus.class, com.hoolai.ccgames.bi.protocol.Common.MessageStatus.Builder.class);
    }

    public static com.google.protobuf.Parser<MessageStatus> PARSER =
        new com.google.protobuf.AbstractParser<MessageStatus>() {
      public MessageStatus parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MessageStatus(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MessageStatus> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int STATUS_FIELD_NUMBER = 1;
    private int status_;
    /**
     * <code>optional int32 status = 1;</code>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 status = 1;</code>
     */
    public int getStatus() {
      return status_;
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 2;
    private java.lang.Object description_;
    /**
     * <code>optional string description = 2;</code>
     */
    public boolean hasDescription() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string description = 2;</code>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          description_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string description = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      status_ = 0;
      description_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, status_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getDescriptionBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, status_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getDescriptionBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.hoolai.ccgames.bi.protocol.Common.MessageStatus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hoolai.ccgames.bi.protocol.Common.MessageStatus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hoolai.ccgames.bi.protocol.Common.MessageStatus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hoolai.ccgames.bi.protocol.Common.MessageStatus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hoolai.ccgames.bi.protocol.Common.MessageStatus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hoolai.ccgames.bi.protocol.Common.MessageStatus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.hoolai.ccgames.bi.protocol.Common.MessageStatus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.hoolai.ccgames.bi.protocol.Common.MessageStatus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.hoolai.ccgames.bi.protocol.Common.MessageStatus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hoolai.ccgames.bi.protocol.Common.MessageStatus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hoolai.ccgames.bi.protocol.Common.MessageStatus prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Common.MessageStatus}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Common.MessageStatus)
        com.hoolai.ccgames.bi.protocol.Common.MessageStatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hoolai.ccgames.bi.protocol.Common.internal_static_Common_MessageStatus_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hoolai.ccgames.bi.protocol.Common.internal_static_Common_MessageStatus_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hoolai.ccgames.bi.protocol.Common.MessageStatus.class, com.hoolai.ccgames.bi.protocol.Common.MessageStatus.Builder.class);
      }

      // Construct using com.hoolai.ccgames.bi.protocol.Common.MessageStatus.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        status_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        description_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hoolai.ccgames.bi.protocol.Common.internal_static_Common_MessageStatus_descriptor;
      }

      public com.hoolai.ccgames.bi.protocol.Common.MessageStatus getDefaultInstanceForType() {
        return com.hoolai.ccgames.bi.protocol.Common.MessageStatus.getDefaultInstance();
      }

      public com.hoolai.ccgames.bi.protocol.Common.MessageStatus build() {
        com.hoolai.ccgames.bi.protocol.Common.MessageStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hoolai.ccgames.bi.protocol.Common.MessageStatus buildPartial() {
        com.hoolai.ccgames.bi.protocol.Common.MessageStatus result = new com.hoolai.ccgames.bi.protocol.Common.MessageStatus(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.status_ = status_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.description_ = description_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hoolai.ccgames.bi.protocol.Common.MessageStatus) {
          return mergeFrom((com.hoolai.ccgames.bi.protocol.Common.MessageStatus)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hoolai.ccgames.bi.protocol.Common.MessageStatus other) {
        if (other == com.hoolai.ccgames.bi.protocol.Common.MessageStatus.getDefaultInstance()) return this;
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (other.hasDescription()) {
          bitField0_ |= 0x00000002;
          description_ = other.description_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hoolai.ccgames.bi.protocol.Common.MessageStatus parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hoolai.ccgames.bi.protocol.Common.MessageStatus) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int status_ ;
      /**
       * <code>optional int32 status = 1;</code>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 status = 1;</code>
       */
      public int getStatus() {
        return status_;
      }
      /**
       * <code>optional int32 status = 1;</code>
       */
      public Builder setStatus(int value) {
        bitField0_ |= 0x00000001;
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 status = 1;</code>
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object description_ = "";
      /**
       * <code>optional string description = 2;</code>
       */
      public boolean hasDescription() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string description = 2;</code>
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            description_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string description = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string description = 2;</code>
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string description = 2;</code>
       */
      public Builder clearDescription() {
        bitField0_ = (bitField0_ & ~0x00000002);
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <code>optional string description = 2;</code>
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        description_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Common.MessageStatus)
    }

    static {
      defaultInstance = new MessageStatus(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Common.MessageStatus)
  }

  public interface MessageIgnoreOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Common.MessageIgnore)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 msg_id = 1;</code>
     */
    boolean hasMsgId();
    /**
     * <code>optional int32 msg_id = 1;</code>
     */
    int getMsgId();
  }
  /**
   * Protobuf type {@code Common.MessageIgnore}
   */
  public static final class MessageIgnore extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Common.MessageIgnore)
      MessageIgnoreOrBuilder {
    // Use MessageIgnore.newBuilder() to construct.
    private MessageIgnore(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MessageIgnore(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MessageIgnore defaultInstance;
    public static MessageIgnore getDefaultInstance() {
      return defaultInstance;
    }

    public MessageIgnore getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MessageIgnore(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              msgId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hoolai.ccgames.bi.protocol.Common.internal_static_Common_MessageIgnore_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hoolai.ccgames.bi.protocol.Common.internal_static_Common_MessageIgnore_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hoolai.ccgames.bi.protocol.Common.MessageIgnore.class, com.hoolai.ccgames.bi.protocol.Common.MessageIgnore.Builder.class);
    }

    public static com.google.protobuf.Parser<MessageIgnore> PARSER =
        new com.google.protobuf.AbstractParser<MessageIgnore>() {
      public MessageIgnore parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MessageIgnore(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MessageIgnore> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int MSG_ID_FIELD_NUMBER = 1;
    private int msgId_;
    /**
     * <code>optional int32 msg_id = 1;</code>
     */
    public boolean hasMsgId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 msg_id = 1;</code>
     */
    public int getMsgId() {
      return msgId_;
    }

    private void initFields() {
      msgId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, msgId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, msgId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.hoolai.ccgames.bi.protocol.Common.MessageIgnore parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hoolai.ccgames.bi.protocol.Common.MessageIgnore parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hoolai.ccgames.bi.protocol.Common.MessageIgnore parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hoolai.ccgames.bi.protocol.Common.MessageIgnore parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hoolai.ccgames.bi.protocol.Common.MessageIgnore parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hoolai.ccgames.bi.protocol.Common.MessageIgnore parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.hoolai.ccgames.bi.protocol.Common.MessageIgnore parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.hoolai.ccgames.bi.protocol.Common.MessageIgnore parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.hoolai.ccgames.bi.protocol.Common.MessageIgnore parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hoolai.ccgames.bi.protocol.Common.MessageIgnore parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hoolai.ccgames.bi.protocol.Common.MessageIgnore prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Common.MessageIgnore}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Common.MessageIgnore)
        com.hoolai.ccgames.bi.protocol.Common.MessageIgnoreOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hoolai.ccgames.bi.protocol.Common.internal_static_Common_MessageIgnore_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hoolai.ccgames.bi.protocol.Common.internal_static_Common_MessageIgnore_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hoolai.ccgames.bi.protocol.Common.MessageIgnore.class, com.hoolai.ccgames.bi.protocol.Common.MessageIgnore.Builder.class);
      }

      // Construct using com.hoolai.ccgames.bi.protocol.Common.MessageIgnore.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        msgId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hoolai.ccgames.bi.protocol.Common.internal_static_Common_MessageIgnore_descriptor;
      }

      public com.hoolai.ccgames.bi.protocol.Common.MessageIgnore getDefaultInstanceForType() {
        return com.hoolai.ccgames.bi.protocol.Common.MessageIgnore.getDefaultInstance();
      }

      public com.hoolai.ccgames.bi.protocol.Common.MessageIgnore build() {
        com.hoolai.ccgames.bi.protocol.Common.MessageIgnore result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hoolai.ccgames.bi.protocol.Common.MessageIgnore buildPartial() {
        com.hoolai.ccgames.bi.protocol.Common.MessageIgnore result = new com.hoolai.ccgames.bi.protocol.Common.MessageIgnore(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msgId_ = msgId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hoolai.ccgames.bi.protocol.Common.MessageIgnore) {
          return mergeFrom((com.hoolai.ccgames.bi.protocol.Common.MessageIgnore)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hoolai.ccgames.bi.protocol.Common.MessageIgnore other) {
        if (other == com.hoolai.ccgames.bi.protocol.Common.MessageIgnore.getDefaultInstance()) return this;
        if (other.hasMsgId()) {
          setMsgId(other.getMsgId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hoolai.ccgames.bi.protocol.Common.MessageIgnore parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hoolai.ccgames.bi.protocol.Common.MessageIgnore) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int msgId_ ;
      /**
       * <code>optional int32 msg_id = 1;</code>
       */
      public boolean hasMsgId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 msg_id = 1;</code>
       */
      public int getMsgId() {
        return msgId_;
      }
      /**
       * <code>optional int32 msg_id = 1;</code>
       */
      public Builder setMsgId(int value) {
        bitField0_ |= 0x00000001;
        msgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 msg_id = 1;</code>
       */
      public Builder clearMsgId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgId_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Common.MessageIgnore)
    }

    static {
      defaultInstance = new MessageIgnore(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Common.MessageIgnore)
  }

  public interface MessageEmptyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Common.MessageEmpty)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code Common.MessageEmpty}
   */
  public static final class MessageEmpty extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Common.MessageEmpty)
      MessageEmptyOrBuilder {
    // Use MessageEmpty.newBuilder() to construct.
    private MessageEmpty(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MessageEmpty(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MessageEmpty defaultInstance;
    public static MessageEmpty getDefaultInstance() {
      return defaultInstance;
    }

    public MessageEmpty getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MessageEmpty(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hoolai.ccgames.bi.protocol.Common.internal_static_Common_MessageEmpty_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hoolai.ccgames.bi.protocol.Common.internal_static_Common_MessageEmpty_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hoolai.ccgames.bi.protocol.Common.MessageEmpty.class, com.hoolai.ccgames.bi.protocol.Common.MessageEmpty.Builder.class);
    }

    public static com.google.protobuf.Parser<MessageEmpty> PARSER =
        new com.google.protobuf.AbstractParser<MessageEmpty>() {
      public MessageEmpty parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MessageEmpty(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MessageEmpty> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.hoolai.ccgames.bi.protocol.Common.MessageEmpty parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hoolai.ccgames.bi.protocol.Common.MessageEmpty parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hoolai.ccgames.bi.protocol.Common.MessageEmpty parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hoolai.ccgames.bi.protocol.Common.MessageEmpty parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hoolai.ccgames.bi.protocol.Common.MessageEmpty parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hoolai.ccgames.bi.protocol.Common.MessageEmpty parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.hoolai.ccgames.bi.protocol.Common.MessageEmpty parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.hoolai.ccgames.bi.protocol.Common.MessageEmpty parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.hoolai.ccgames.bi.protocol.Common.MessageEmpty parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hoolai.ccgames.bi.protocol.Common.MessageEmpty parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hoolai.ccgames.bi.protocol.Common.MessageEmpty prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Common.MessageEmpty}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Common.MessageEmpty)
        com.hoolai.ccgames.bi.protocol.Common.MessageEmptyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hoolai.ccgames.bi.protocol.Common.internal_static_Common_MessageEmpty_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hoolai.ccgames.bi.protocol.Common.internal_static_Common_MessageEmpty_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hoolai.ccgames.bi.protocol.Common.MessageEmpty.class, com.hoolai.ccgames.bi.protocol.Common.MessageEmpty.Builder.class);
      }

      // Construct using com.hoolai.ccgames.bi.protocol.Common.MessageEmpty.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hoolai.ccgames.bi.protocol.Common.internal_static_Common_MessageEmpty_descriptor;
      }

      public com.hoolai.ccgames.bi.protocol.Common.MessageEmpty getDefaultInstanceForType() {
        return com.hoolai.ccgames.bi.protocol.Common.MessageEmpty.getDefaultInstance();
      }

      public com.hoolai.ccgames.bi.protocol.Common.MessageEmpty build() {
        com.hoolai.ccgames.bi.protocol.Common.MessageEmpty result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hoolai.ccgames.bi.protocol.Common.MessageEmpty buildPartial() {
        com.hoolai.ccgames.bi.protocol.Common.MessageEmpty result = new com.hoolai.ccgames.bi.protocol.Common.MessageEmpty(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hoolai.ccgames.bi.protocol.Common.MessageEmpty) {
          return mergeFrom((com.hoolai.ccgames.bi.protocol.Common.MessageEmpty)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hoolai.ccgames.bi.protocol.Common.MessageEmpty other) {
        if (other == com.hoolai.ccgames.bi.protocol.Common.MessageEmpty.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hoolai.ccgames.bi.protocol.Common.MessageEmpty parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hoolai.ccgames.bi.protocol.Common.MessageEmpty) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Common.MessageEmpty)
    }

    static {
      defaultInstance = new MessageEmpty(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Common.MessageEmpty)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Common_MessageLogin_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Common_MessageLogin_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Common_MessageStatus_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Common_MessageStatus_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Common_MessageIgnore_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Common_MessageIgnore_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Common_MessageEmpty_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Common_MessageEmpty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Common.proto\022\006Common\"i\n\014MessageLogin\022\020" +
      "\n\010platform\030\001 \001(\t\022\016\n\006app_id\030\002 \001(\t\022\022\n\nlogi" +
      "n_name\030\003 \001(\t\022\022\n\nlogin_pass\030\004 \001(\t\022\017\n\007msg_" +
      "ver\030\005 \001(\005\"4\n\rMessageStatus\022\016\n\006status\030\001 \001" +
      "(\005\022\023\n\013description\030\002 \001(\t\"\037\n\rMessageIgnore" +
      "\022\016\n\006msg_id\030\001 \001(\005\"\016\n\014MessageEmptyB(\n\036com." +
      "hoolai.ccgames.bi.protocolB\006Common"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Common_MessageLogin_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Common_MessageLogin_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Common_MessageLogin_descriptor,
        new java.lang.String[] { "Platform", "AppId", "LoginName", "LoginPass", "MsgVer", });
    internal_static_Common_MessageStatus_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Common_MessageStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Common_MessageStatus_descriptor,
        new java.lang.String[] { "Status", "Description", });
    internal_static_Common_MessageIgnore_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Common_MessageIgnore_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Common_MessageIgnore_descriptor,
        new java.lang.String[] { "MsgId", });
    internal_static_Common_MessageEmpty_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Common_MessageEmpty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Common_MessageEmpty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
